### ISSUE TITLE
Error C1-6703-6 when launching rePatched Idol Magical Girl Chiru Chiru Michiru

### ISSUE THREAD

**Issue by mancupo** [dots-tb/reF00D#7]
Grisaia.no.Kajitsu.Spinout.Idol.Mahou.Shoujo.ChiruChiru.Michiru.JAP.PCSG00620.NoNpDRM by itself will boot, but when it is patched with [NStC] GrisaianoKajitsuSpinoutVitaEN_v0.51_NoNpDrm (English Patch using latest rePatch) it will give the above C1-6703-6 error.  Disabling reFOOD inside config.txt will make the patched game work.  Vita is on v3.65.

**Comment by mancupo** [comment]
https://gbatemp.net/threads/release-grisaia-series-vita-english-ports-labyrinth-eden-spinout.475386/

**Comment by CelesteBlue-dev** [comment]
@dots-tb to investigate

**Comment by ZayedHegazi** [comment]
Same problem ;-;

**Comment by ZayedHegazi** [comment]
Same problem ;-;

**Comment by Princess-of-Sleeping** [comment]
~~@mancupo Can You test with the latest release?~~

This is a translation tool issue, not a reF00D issue.

The translation tool decrypts and rebuilds eboot.bin, but does not re-encrypt the program segment.
It also does not clear the signed header.

Therefore, reF00D succeeds in authenticating the header, but since the program segment is not re-encrypted, it tries to decrypt and decompress the decrypted program segment again, but decrypting the unencrypted segment program produces garbage. As a result, the vita system cannot decompress and returns an error.

**Comment by Princess-of-Sleeping** [comment]
A temporary workaround for this issue is to use a hex editor to clear the eboot.bin offsets from 0x630 to 0x1000 with zeros.

**Comment by Princess-of-Sleeping** [comment]
Well, clearing 0x630-0x640 with zeros, should also work.
